---
title: "003 - Review of literature"
author: "Karel Räpp, Henry Enno Turu"
date: "28 11 2020"
output: 
  bookdown::pdf_document2:
    toc: no
csl: apa.csl
bibliography: library.bib
indent: yes
fontsize: 12pt
geometry: margin = 1in
link-citations: yes
linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \usepackage{microtype}
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage{float}
- \usepackage{amsmath}
- \DeclareMathOperator{\logit}{logit}
---
\graphicspath{ {./images/} }


# Review of literature
## Link between financial markets & real economy
 
Firstly, to dig deeper into various variables that help to predict future macroeconomic conditions, it is essential to understand what are the mechanisms that can explain the connection of the financial markets and the real economy. 
 
One of the best examples can be made on the basis of the global financial crisis and using one of the most important concepts of macroeconomic theory - Fischer theory. According to the formula, the nominal interest rate is equal to the real interest rate and expected inflation/deflation. So, as the expected inflation rate changes, equilibrium is reached by changing the nominal interest rate. On the basis of this example, if we expect future deflation which over a longer time period implicitly refers to recession, we can see that it also affects the current market situation.


## Volatility as a predictor of GDP
As the studies about first moments of financial variables have become fairly obsolete, researchers have started focusing on another level - e.g. (implied) volatilities. @Fornari2019 use the countercyclicality of financial volatility to construct a prediction model and conclude that stock volatility is a significant variable in predicting business cycles. The conclusion is even stronger when combining volatility with term spread - in such a case, their proposed model would have predicted at least 3 of the last recessions. @Ferrara2014 continue the same path - they mix daily financial volatility with monthly industrial production and achieve significant results in predicting GDP; nevertheless their results are limited to the timeframe of Great Recession in 2008-2009.

Similarly to stock prices, option prices reflect future expectations. Taking this into account, @David2014 continue to discover implications of at-the-money (ATM) implied volatility (IV). They find that a positive shock to stock and bonds ATM IV is followed by a decline in future real rates and decrease j probability of deflation. Thus, there exists a positive relationship between IV shock and possibility of recession.

Building upon the aforementioned various research, @Cremers2021 have analyzed over 20 years of data to find out whether Treasury yield implied volatility can be used to predict different macroeconomic and financial measures such as growth & volatility of GDP, industrial production, employment. Using daily at-the-money option data from 1990 May until 2016 November for different treasury bonds and bills, they calculated daily (treasury) implied volatilities (YIV) using Black’s model, which in essence is an adjusted model of the famous Black & Scholes model to value options on future contracts [@Black1976] - see equation \@ref(eq:black).


\begin{equation}\
c = e^{-rT} + [FN(d_{1})-KN(d_{2})] (\#eq:black)
\end{equation}

where 

\begin{align}
d_{1} = \frac{ln (F/K) + 0.5\sigma_{t}^{2}]}{\sqrt{\sigma T}} && d_{2} = d_{1} - \sqrt{\sigma T}
 \end{align}

C refers to the price of a call option, F is the price of the underlying future, T is the time to expiration, sigma the volatility of the underlying asset, r is the interest rate. Using the formula and deriving sigma, one can compute the (treasury) implied volatility.


The options are chosen on the basis of exercise price being closest to the price of the underlying bond future - i.e. then its closest to at-the-money. This is done because @Ederington1993 & [-@Ederington1996] argue that contracts that are closest to at-the-money possess a strong link between spot and future markets. Therefore, these options can be treated as they are options on the bond spot market itself. Furthermore, they argue that those options tend to be the most liquid ones.

After obtaining the daily time series of implied volatility, the authors simply average the daily time series to obtain monthly data, which is regressed with different macroeconomic & control variables.


\begin{equation}
\sum_{j=1}^{j=H} log(1+GDP_{i,t+j}) = \alpha_{H}+ \beta_{H} \sigma_{IV,t} + Controls +\varepsilon_{t+H}
\end{equation}

So, for example, in the main regression described by the formula above, the authors analyze the effect on GDP. In this case, GDP refers to quarterly year-on-year growth rate. It is important to notice that they use the average annualized growth rate that is obtained by dividing the sum of quarterly growth rates with the number of quarters forecasted H.

To validate YIV ability to forecast GDP growth, several control variables such as term spreads, credit spreads, stock market volatility, housing starts, etc. are included in the model. The selection of housing starts (amount of residential property construction projects started) is justified in a research by @Ewing2005 who find that economic cycles are positively correlated with housing starts. In addition, @Cesa-Bianchi2020 offer a multi-country overview on the connection of realized stock market volatility and real output growth, where they report significant correlation between the two. Regardless of not directly using VIX as a measure for volatility, the conclusion should hold for VIX as well - the comovement of VIX and their constructed realized volatility measure is very similar, having correlation of over 90%. Additionally, term spreads have been a key element connected to forecasting recession, which is also verified by @Ang2006 - furthermore, they identify that short rate is the best predictor among all of the term spreads. To complement, @Wright2006 advances the findings further and reports higher performance in forecasting GDP with term spreads and federal funds rates together. Lastly, @Gilchrist2012 construct a corporate bond credit spread index which not only is a significant predictor of macroeconomic activity for different variables & time-horizons but also its predictive ability outperforms commonly used BAA-AAA corporate bond spread.


Even though the authors possess the data for different maturities (1,5,10,30 years), the research concluded that specifically a 5-year Treasury note significantly predicts most of the aforementioned elements - even after controlling for many other predictors named before. This is in line with the findings of @Brandt2007 who identify that the price discovery tends to mostly happen in contracts with maturity of 5-year, both for cash and future markets.

## Forecasting asymmetries
In the fairly recent wave of research of forecasting, the problems and limitations regarding full-sample forecasting have become more prevalent. More specifically, it has been found that the business cycles have a statistically significant effect on the model’s predictive ability. Furthermore, through using state-dependent models, the effects of business cycle asymmetries can be evaluated on the forecasting performance of the model.

For example, in the Handbook of Economics, @Chauvet2013 evaluate the accuracy of different models with regards to the performance during recessionary periods and expansionary periods using the classifications for US recessions and expansions from National Bureau of Economic Research (NBER). They conclude that for all different models tested, the GDP growth is significantly harder to forecast during recessions when compared to expansionary periods. Furthermore, based on the results they state that although the forecasting ability of some of the models is relatively good during expansions, most of them fail during recessions. 

In addition, @Siliverstovs2021 adds to the research by analyzing the impact of influential observations on relative forecast accuracy during Covid-19 crisis. By employing a newly proposed metric (recursive relative mean squared forecast error) together with the cumulative sum of squared forecast error difference (CSSFED) presented in @Welch2008, he concludes that there exist significant differences in relative forecasting error depending on the business cycle.^[Note:a more detailed description can be found in the section "Methodology".]

Therefore, there is reason to believe that the model introduced by Cremers & Fleckenstein & Gandhi might not offer significant information about the future during calm days. Arising from this, we replicate their models while accounting for the effects of different economic phases and see whether it still offers a robust outcome.



## Advanced methods for macroeconomic forecasting
Based on the recent research on forecasting, there is significant evidence on the poor performance of simple autoregressive models when forecasting macroeconomic real activity.
In an IMF working paper “Deus ex Machina? A Framework for Macro Forecasting with Machine Learning” published in February 2020, Bolhuis and Rayner bring out the following four key shortcomings of a simple OLS-based forecasting model: Collinearity, Dimensionality, Predictor relevance, and Non-linearity. The latter is also emphasized by @Chauvet2013, who summarize that the biggest errors of linear models happen during the recessionary periods as in the beggining or the end of the period linear relationships break. Hence, non-linear models compared to linear models can improve the forecasting performance and output additional information.

Also, to combat some of these shortcomings (collinearity and dimensionality), @Siliverstovs2020 assessed the forecasting performance of a dynamic factor model (DFM) compared to a simple autoregressive model. Furthermore, they also included the state-dependent subsamples to their research. The main finding is that there is a significant performance improvement in forecasting capability during the recessionary periods when using the dynamic factor model. Thus, it further illustrates the need for accounting the state-dependency and the importance of using more advanced models (especially during the recessionary periods) over simple autoregressive models to account for the shortcomings of simple OLS-based models.

However, for our research, using a DFM doesn't serve its purpose as we are using a limited set of proven control variables which diminish the problems of collinearity and dimensionality significantly. Furthermore, as brought out by @Bolhuis2020, while the DFM-s account for collinearity and dimensional shortcomings, they are still unable to account for the predictor relevance and non-linearity. This in turn increases the root mean square forecast errors (RMSFE) and thus, makes the predictions less accurate.

A solution for this can be found through implementing machine learning (ML) models which have been increasingly taken into use also in applied economics research. Researches have been drawn more and more towards the ML methods in forecasting mainly due to its ability to take into account nonlinearity and its emphasis on out-of-sample forecasting to avoid overfitting which in turn improves the performance with regards to the forecasting accuracy and robustness [@Carrasco2016]. Furthermore, through ML methods we will be able to test for predictor relevance to get an overview of how significant variable YIV is in predicting macroeconomic real activity and how does it compare against other academically proven predictors.


To take it together, our paper builds upon @Cremers2021 while improving the methodology in 2 ways:

1. Checking whether YIV helps to predict GDP growth controlling for 3 different definitions
1. Testing YIV's predictive ability depending on the business cycle
2. Introducing machine learning method in search of more accurate forecasting performance

Proceedingly, our hypotheses are the following: 

***Hypothesis 1.*** The treasury bond implied volatility (YIV) is a significant predictor of future macroeconomic real activity.

***Hypothesis 2.*** Due to the business-cycle related asymmetries, the model based on the full-sample forecasts is inefficient in predicting during turbulent time periods.

***Hypothesis 3.*** Using machine learning methods, it is possible to significantly reduce the RMFSE of the forecast mainly thanks to its ability to take into account non-linearity.
