---
title: "005 - Data"
author: "Karel Räpp, Henry Enno Turu"
date: "28 11 2020"
output: 
  bookdown::pdf_document2:
    toc: no
csl: apa.csl
bibliography: library.bib
indent: yes
fontsize: 12pt
geometry: margin = 1in
link-citations: yes
linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \usepackage{microtype}
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage{float}
- \usepackage{amsmath}
- \DeclareMathOperator{\logit}{logit}
---

```{r }
library(readr)
library(ggplot2)
library(knitr)
```

\graphicspath{ {./images/} }



# Data & descriptive statistics

For the regression analysis, we have extracted the following data:

* Quarterly 5-year Treasury Implied Volatility 
* Quarterly GDP year-on-year growth rate
* Control Variables
  5. US treasury interest rates to construct term spreads
  6. credit spreads
  7. credit spread index
  8. stock returns (SPY)
  9. stock market implied volatility (VIX)
  10. Residential market construction starts


As mentioned in the review of literature, YIV is constructed using Black model & deriving implied volatility through option prices, time-to-maturity, etc. The data regarding options on treasury bond futures, however, is collected by CME and available only through accessing their database.

Due to the data price being behind the paywall, we had to resort to other measures to access the data. Firstly, we contacted prof. Cremers, Gandhi & Fleckenstein, who were ready to share their data with us if the CME group gives their consent. Nevertheless, as the work is still in the publication process, we could not rely solely on that possibility, and thus resort to other options - extracting data via plot digitizers (read more in Appendix A.)



The data regarding GDP year-on-year growth rate was extracted on a quarterly basis from @Alfred2020. Furthermore, the vintage 2019-12-20 was extracted as it coincided the best with the data used in the research paper by @Cremers2017. In addition, most of the data for constructing control variables were also extracted from the Fred database, such as:
 
* Quarterly risk free rates (Treasury constant maturity rates for 3 month, 6 months, 1 year, 5 year and 10 year) 
* Quarterly corporate bond yields
  * Moody’s seasoned AAA corporate bond 
  * Moody’s seasoned BAA corporate bond
* Quarterly housing (new residential property construction) starts

In addition to individual corporate bonds yields, we have also added corporate bond credit spread index by Gilchrist and Zakrajsek (2012), which was obtained from the official replication dataset   OPENCSR[@GZdata]. As per authors, the index Lastly, the daily data for stock market implied volatility (VIX) is taken from CBOE, which is later aggregated into quarterly data [@vix]. The monthly SPY historical data is obtained from Yahoo Finance, which again is aggregated into quarterly data [@spy].

We use the risk free rates to compute different term spreads which is defined as the difference

* between 10 year and 12 month treasury constant maturity rate (variable TRM1012). 
* between 10 year and 6 month treasury constant maturity rate (variable TRM1006).
* between 10 year and 3month treasury constant maturity rate (variable TRM1003) 
* between 5 year and 6 month treasury constant maturity rate (variable TRM0506)
* between 5 year and 3 month treasury constant maturity rate (variable TRM0503)

Furthermore, we construct changes in the short rate that is defined as the change in the rate of treasury 3 month note (SRT03M). In addition to the credit spread index(CRSZGI) and individual corporate yields, we calculate yield spread between AAA and BAA corporate bonds, defined as baa_aaa. All the used variables prior to standardization can be seen in Table \@ref(tab:summarystat)

