---
title: "Results"
author: "Karel Räpp, Henry Enno Turu"
date: "29 11 2020"
output: 
  bookdown::pdf_document2:
    toc: no
csl: apa.csl
bibliography: library.bib
indent: yes
fontsize: 12pt
geometry: margin = 1in
link-citations: yes
linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \usepackage{microtype}
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage{float}
- \usepackage{amsmath}
- \DeclareMathOperator{\logit}{logit}
---


# Results

## In-sample regressions

We first begin by regressing YIV to GDP growth throughout different rolling periods - i.e. 4, 6, 8, 10 and 12 quarter GDP growth rolling averages (the regression formula and summary can be seen in appendix D). Our regression results implicate that 1 standard deviation increase in YIV is associated with a -1 * 1.31% = 1.31% decrease in gdp growth within next 4 quarters.  For predicting 12 quarters ahead (3 years), 1 standard deviation increase in YIV is associated with a -0.54 * 1.31% * 3 = 2.11% decrease in GDP growth. To illustrate the magnitude of this reduction, one should note that the average year-on-year growth rate in our sample is 2,5%.

Furthermore, it can be seen, YIV’s coefficients are significant throughout the prediction periods within 1% confidence level. The model’s R-squared gradually decreases from 39% in predicting ahead GDP growth 4 quarters’ rolling averages to 19% in predicting ahead 12 quarters’ rolling averages. These results are consistent with the paper by @Cremers2017 while the only difference is from std. error. Thus, this verifies the validity of our methodology and that the extracted data can be used to proceed with the research process. Nevertheless, as an additional robustness check to ensure that YIV predicts GDP growth and not the other way around, we run the Granger causality test by which we indeed conclude that YIV granger-caused GDP growth. 

Next, we add a dummy variable representing recessionary periods (according to the NBER classification) i.e. the dummy takes a value of 1 during recession and 0 during expansion (appendix E). As it can be seen from the table, the dummy’s coefficient is negative and significant at 1% confidence level throughout all predicted timespans. Furthermore, adding the dummy improved R-squared significantly - 61% in predicting ahead GDP growth 4 quarters’ rolling averages when compared to 39% of respective YIV only model. The latter indicates that there is a structural break in data during recessions and that full model predictions during recessionary periods can result in poor prediction accuracy. Nevertheless, the interaction term of the dummy variable & YIV yield insignificant results. Hence, this means that recessionary period only influences the intercept, not slope of the variable.

Next, we construct a model with YIV and two lagged GDP growth values (i.e. GDP growth 1 and 2 quarters ago) chosen through AIC information criteria (appendix F), in order to see if the YIVs predictive ability persists. 
Additionally, we also constructed a model with two lagged GDP growth values and controls as regressors (appendix G). The controls variables were selected among the variables described in the data section. More specifically, the following controls were selected initially: DGS1, DGS5, DGS10, DGS3MO, DGS6MO, TRM0503, TRM0506, TRM1003, TRM1006, TRM1012, STR03M, BAA-AAA, VIX, HOUSNG and GZ_SPR. However, due to multicollinearity problems among DSG and TRM controls we constructed a model for variable selection and  selected the best predictor among those groups. For selection criteria, both R-squared and Mallow’s Cp were used and according to this we chose DGS10 and TRM1012 as the best predictors out of DGS and TRM control groups. Thus, in the final regression model the following controls were included: DGS1, TRM1012, STR03M, BAA-AAA, VIX, HOUSNG and GZ_SPR.
Finally, we included all the aforementioned independent variables to one regression equation (appendix H). As it can be seen, even when including the lags of GDP growth and all the relevant control variables, the YIV still remains a significant predictor throughout all the periods. In the final model, the regression results implicate that 1 standard deviation increase in YIV is associated with a -0.48 * 1.31% = 0.63% decrease in gdp growth within next 4 quarters (1% confidence level). Additionally, when predicting 12 quarters ahead a 1 standard deviation increase in YIV is associated with a -0.25* 1.31% * 3 = 0.98% decrease in the next 12 quarters’ average annualized growth rate within a 10% confidence level.
The latter regression indicates that, although accounting for many of the most significant variables with regards to the GDP growth prediction, the YIV’s predictive ability still persists meaning that YIV can be considered as a solid indicator of GDP growth.


## Out of sample forecasting
### Full sample

Lastly, we were not only interested in the in-sample performance of the variable. Hence, we constructed out-of-sample regressions to compute RMSFE-s of full-sample and subsample models (results can be seen in appendix I). For the out-of-sample regressions we used 5 year rolling windows and predicted ahead 1 to 12 quarters. As it can be seen from the table and graph the full-sample out-of-sample RMSFE-s rose steadily up until predicting 9 quarters ahead and then slightly dropped. In other words, the interpretation of it was that YIV-s accuracy in predicting GDP growth got worse in predicting further time periods with a slight improvement from the 10th quarter. 

### Sub-sample OOS forecasting

Next, we wanted to compare the full-sample OOS RMSFE-s with the subsample OOS RMSFE-s. As it can be seen, during the recessionary period the RMSFE is significantly higher when compared to the full-sample RMSFE. This confirms our second hypothesis i.e. the full-sample is not robust in making predictions during turbulent time periods as the accuracy of the model suffers tremendously. During the expansionary periods the OOS RMSFE impoves slightly which is in line with the hypothesis as the inaccuracies of the expansionary periods are filtered out.

## Macroeconomic Random Forest

