---
title: "002 - Introduction"
author: "Karel Räpp, Henry Enno Turu"
date: "28 11 2020"
output: 
  bookdown::pdf_document2:
    toc: no
csl: apa.csl
bibliography: library.bib
indent: yes
fontsize: 12pt
geometry: margin = 1in
link-citations: yes
linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \usepackage{microtype}
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage{float}
- \usepackage{amsmath}
- \DeclareMathOperator{\logit}{logit}
---



\linespread{1.6}\selectfont

# Introduction


Forecasting the real economy has been a widely researched topic as it is crucial for effective policymaking. Furthermore, one of the most-used channel for forecasting the real economy is through financial markets as these markets (be it equity, fixed income, or commodity markets) incorporate a significant amount of forward-looking information regarding the performance of the real economy.
  
One of the most comprehensive papers quantifying the financial market's ability to forecast the macroeconomic real activity was published by @Stock2003. The researchers reviewed over 93 working papers & articles and documented numerous variables (interest rates, term spreads, returns, exchange rates, etc.) that have been used for forecasting the macroeconomy. Nevertheless, there is no firm agreement on which can do so consistently, as per the conclusion made: ”Some asset prices have been useful predictors of inflation and/or output growth in some countries in some time periods” [@Stock2003, p. 822]. Furthermore, there are even fewer variables that can predict the macroeconomic real activity through more extended periods (i.e. periods of over a year). 

In a recent work by @Cremers2021, they approach predicting the macroeconomic real activity through the treasury implied volatility (YIV) which is calculated using options on treasury bond futures of different maturity periods. YIV can be considered as a measure for interest rate uncertainty as it incorporates market participants' sentiment towards the future outlook for interest rates on which the underlying asset (Treasury bond) is dependent. In the paper, the authors show that YIV is able to forecast the real economy consistently, especially focusing on forecasting the growth of the real GDP as it can be considered as one of the key proxies for the real economy.


As our paper builds on the initial discoveries of @Cremers2021, the first part of our paper focuses on replication their results to test the validity - i.e. whether the growth rate of real GDP can be predicted using YIV.

In the second part of the research, we advanced their paper from two perspectives.

Firstly, to account for the state-dependency of forecast models as shown to be relevant by @Chauvet2013 and @Siliverstovs2020, we test whether business cycles affect the size of YIV's impact on future GDP growth. In addition, we investigate whether out-of-sample forecast performance is dependent on the business cycle - i.e. calculating RMSFE including only recessionary periods or expansionary periods (classification of the US business cycles obtained from NBER).

Secondly, we propose using machine learning models to account for the shortcomings of the simple OLS-based models. More specifically, the inability of simple OLS-based models to account for collinearity, dimensionality, predictor relevance and non-linearity [@Bolhuis2020]. To elaborate, we apply the framework of a random forest (RF) model as it is able to tackle the aforementioned problems [@Coulombe2020]. Thus, the RF model is expected to significantly decrease the root mean square forecasting errors (RMSFE). Nevertheless, its output is difficult to interpret, but as it is not the main scope of our research, we do not consider it a problem.
  
Thus, our research question consists of three sub-questions:

1. **Can options on Treasury bond futures effectively predict USA's macroeconomic activity?**
2. **If so, is this conclusion robust even after considering different business cycles and control variables.**
3. **Do Machine Learning methods such as Random Forest improve the forecast accuracy?**

The research paper is structured as follows. First, we offer context to our work by describing various research already done in the same field. As the next step, we describe the data and the acquisition method used for obtaining it. Subsequently, we offer an in-depth overview of the methods used, which is followed by a description of the results. In the discussion part, we elaborate on how our findings fit in with the existing research. Lastly, we list any possible limitations of the paper and suggest ideas for further research.


