---
title: "003 - Review of literature"
author: "Karel Räpp, Henry Enno Turu"
date: "28 11 2020"
output: 
  bookdown::pdf_document2:
    toc: no
csl: apa.csl
bibliography: library.bib
indent: yes
fontsize: 12pt
geometry: margin = 1in
link-citations: yes
linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \usepackage{microtype}
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage{float}
- \usepackage{amsmath}
- \DeclareMathOperator{\logit}{logit}
---
\graphicspath{ {./images/} }


# Review of literature
 
Before digging deeper into the predictive ability of YIV, it is essential to understand the other variables that can explain the connection between financial markets and the real economy. 


## Historically recognized predictors of GDP

One of the most recognized predictors of recessions and GDP growth are term spreads. Moreover, term spreads have been included as one of the most important variables in the business cycle indicator index by @Stock1989. @Ang2006 follow a similar route and use yield curve to obtain the best maturity short rate for forecasting GDP. Using the process above, they conclude that contrarily to the existing research, short rate is a better predictor compared to any of the term spreads. Furthermore, it is noted that the best form of the slope is the one constructed with maximum maturity difference. Lastly, @Gilchrist2012 construct a corporate bond credit spread index which is not only a significant predictor of macroeconomic activity for different variables and time-horizons but also its predictive ability outperforms commonly used BAA-AAA corporate bond spread.

One somewhat different variable that can be potentially used for macroeconomic forecasting is housing starts (amount of residential property construction projects started) as it has been found to be positively correlated with economic cycles [@Ewing2005].

@Fornari2019 use the countercyclicality of financial volatility to construct a prediction model and conclude that stock volatility is a significant variable in predicting business cycles. The conclusion is even stronger when combining volatility with term spread - in such a case, their proposed model would have predicted at least 3 of the last recessions. @Ferrara2014 continue a similar path - they mix daily financial volatility with monthly industrial production and achieve significant results in predicting GDP; nevertheless, their results are limited to the timeframe of the Great Recession in 2008-2009. In addition, @Cesa-Bianchi2020 offer a multi-country overview on the connection of realized stock market volatility and real output growth, where they report a significant correlation between the two. Regardless of not directly using VIX as a measure for volatility, the conclusion should hold for VIX as well - the comovement of VIX and their constructed realized volatility measure is very similar, having a correlation of over 90%.

Similarly to stock prices, option prices reflect future expectations. Taking this into account, @David2014 continue to discover implications of at-the-money (ATM) implied volatility (IV). They find that a shock to stock and bonds ATM IV is followed by a decline in future real rates. Thus, there exists a positive relationship between IV shock and the possibility of a recession.

## Treasury implied volatility as a predictor of real activity

Building upon the various aforementioned researches, @Cremers2021 have analyzed over 20 years of data to find out whether YIV could be used to predict different macroeconomic and financial measures such as growth and volatility of GDP, industrial production, employment. Using daily at-the-money option data from 1990 May until 2016 November for different treasury bonds and bills, they calculated daily YIV series using Black’s model, which in essence is an adjusted model of the famous Black-Scholes model to value options on futures contracts [@Black1976] - see Equation \@ref(eq:black).


\begin{equation}\
c = e^{-rT} + [FN(d_{1})-KN(d_{2})] (\#eq:black)
\end{equation}

where 

\begin{align}
d_{1} = \frac{ln (F/K) + 0.5\sigma_{t}^{2}]}{\sqrt{\sigma T}} && d_{2} = d_{1} - \sqrt{\sigma T}
 \end{align}

C refers to the price of a call option, F is the price of the underlying future, T is the time to expiration, sigma the volatility of the underlying asset, r is the interest rate. Using the formula and deriving sigma, one can compute YIV.


The options are chosen on the basis of exercise price being closest to the price of the underlying bond future - i.e. then its closest to at-the-money. This is done because @Ederington1993 & [-@Ederington1996] argue that contracts that are closest to at-the-money possess a strong link between spot and futures markets. Therefore, these options can be treated as they are options on the bond spot market itself. Furthermore, they argue that those options tend to be the most liquid ones.

After obtaining the daily time series of implied volatility, the authors average the time series to obtain monthly data, which is regressed with different macroeconomic and control variables.


\begin{equation}
\frac{1}{H} \sum_{j=1}^{j=H} log(1+GDP_{t+j}) = \alpha_{H}+ \beta_{H} \sigma_{IV,t} + Controls +\varepsilon_{t+H}
\end{equation}

where $GDP_{i,t+j}$ refers to forward-looking GDP, $\sigma_{IV,t}$ to YIV at time t.


So, for example, in the main regression described by the formula above, the authors analyze YIV's effect on the growth rate of GDP. The left-hand-side of the equation depicts the average annualized growth rate obtained by dividing the sum of quarterly growth rates by the number of quarters forecasted H.

To validate YIV's ability to forecast GDP growth, several aforementioned control variables such as term spreads, credit spreads, stock market volatility, housing starts, etc., are included in the model. 

Even though the authors possess the data for different maturities (1,5,10,30 years), the researchers concluded that specifically, a 5-year Treasury note significantly predicts most of the aforementioned elements - even after controlling for many other predictors named before. This is in line with the findings of @Brandt2007, who identify that the price discovery tends to mostly happen in contracts with a maturity of 5-year, both for cash and futures markets.

## Forecasting asymmetries
In the relatively recent wave of research on forecasting, the problems and limitations regarding full-sample forecasting have become more prevalent. More specifically, it has been found that the business cycles have a statistically significant effect on the model’s predictive ability. Furthermore, through accounting for state-dependency, the effects of business cycle asymmetries can be evaluated on the forecasting performance of the model.

For example, in the Handbook of Economics, @Chauvet2013 evaluate the accuracy of different models with regards to the performance during recessionary periods and expansionary periods using the classifications for the US recessions and expansions from the National Bureau of Economic Research (NBER). They conclude that for all different models tested, the GDP growth is significantly harder to forecast during recessions when compared to expansions. Furthermore, based on the results, they state that although the forecasting ability of some of the models is relatively good during expansions, most of them fail during recessions. 

Therefore, there is reason to believe that the model introduced by @Cremers2021 might not be robust throughout the different business cycles. Arising from this, we replicate their models while accounting for the effects of different economic phases and see whether it still offers a robust outcome.



## Advanced methods for macroeconomic forecasting
Based on the recent research on forecasting, there is significant evidence on the poor performance of simple autoregressive models when forecasting macroeconomic real activity.
In an IMF working paper, “Deus ex Machina? A Framework for Macro Forecasting with Machine Learning”, @Bolhuis2020 bring out the following four key shortcomings of a simple OLS-based forecasting model: collinearity, dimensionality, predictor relevance, and nonlinearity. The latter is also emphasized by @Chauvet2013, who summarize that the biggest errors for linear models occur near the recessionary periods as the linear relationships tend to break.

To combat some of these shortcomings (mainly collinearity and dimensionality), @Siliverstovs2020 assessed the forecasting performance of a dynamic factor model (DFM) compared to a simple autoregressive model. Furthermore, they also included the state-dependent subsamples in their research. The main finding is that there is a significant performance improvement in forecasting capability during the recessionary periods when using the dynamic factor model. In addition, @Siliverstovs2021 adds to the research by analyzing how influential observations affect relative forecast accuracy during the Covid-19 crisis. By employing a cumulative sum of squared forecast error difference (CSSFED) presented in @Welch2008, he concludes that there exist significant differences in relative forecasting error depending on the business cycle^[Note: a more detailed description can be found in the section "Methodology".]. Thus, it further illustrates the need for accounting the state-dependency and the importance of using more advanced models (especially during the recessionary periods) over simple autoregressive models.

To put it simply, some of the key properties of DFM are its ability to work with large datasets with high dimensional data and predicting comovements of many macroeconomics variables (@Stock2016). In our research, however, we are using a limited set of proven control variables (as was done by @Cremers2021) and focusing on predicting only one variable - the growth rate of GDP. Thus, for our research, using a DFM doesn't serve its purpose.

However, another solution to account for some of the shortcomings of simple OLS based models can be found through implementing machine learning (ML) models, which have been increasingly taken into use also in applied economics research. Researches have been drawn more and more towards the ML methods in forecasting mainly due to its ability to take into account nonlinearity and its emphasis on out-of-sample forecasting to avoid overfitting, which in turn improves the performance with regards to the forecasting accuracy and robustness [@Carrasco2016]. Furthermore, through ML methods, we will be able to test for predictor relevance to get an overview of how important YIV is in predicting macroeconomic real activity and how does it compare against other academically proven predictors.


To sum up, our paper builds upon @Cremers2021 while advancing the methodology in 2 ways:

1. Testing YIV's predictive ability depending on the business cycle
2. Introducing machine learning method in search of more accurate forecasting performance

Thus, our hypotheses are the following: 

***Hypothesis 1.*** YIV is a significant predictor of future macroeconomic real activity.

***Hypothesis 2.*** Due to the business-cycle related asymmetries, the model proposed by @Cremers2021 is inefficient in predicting during turbulent time periods.

***Hypothesis 3.*** Using Random Forest, it is possible to significantly reduce the RMFSE of the forecast, mainly thanks to its ability to take into account nonlinearity.
