---
title: "Discussion"
author: "Karel Räpp, Henry Enno Turu"
date: "28 11 2020"
output: 
  bookdown::pdf_document2:
    toc: no
csl: apa.csl
bibliography: library.bib
indent: yes
fontsize: 12pt
geometry: margin = 1in
link-citations: yes
linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \usepackage{microtype}
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage{float}
- \usepackage{amsmath}
- \DeclareMathOperator{\logit}{logit}
---



\linespread{1.6}\selectfont

# Discussion
 
In the following section, we offer context from the literature review to our findings. The goal is to analyze how our results fit in with the existing research by other academia. Secondly, we give an overview of the limitations of our research and, additionally, suggest opportunities for further research on this topic.

## Discussion of results

Based on the results stated previously, we can accept the stated hypothesis 1 that treasury implied volatility is indeed a significant predictor throughout the periods from 1 to 8 quarters ahead. This outcome is robust even after including various control variables that have been historically important predictors of real output, such as term spreads, credit spreads, stock market implied volatility, and new residential construction starts. The latter indicates that although accounting for many of the most significant variables, the YIV’s predictive ability persists meaning that YIV can be considered as a solid indicator of GDP growth.
In general, our results are consistent with the paper by @Cremers2021 verifying the validity of our methodology and that the extracted data can be used for other parts of the research.

Next, the aim was to test the robustness of the model and variable with respect to subsample periods (expansionary and recessionary periods) as from recent literature, there is significant evidence that performance asymmetries concerning subsample periods exist. For example, @Chauvet2013 conclude that GDP growth is significantly more difficult to predict during recessionary periods. To test it, we include a dummy variable in the regression, taking a value of 1 during recessions and 0 during expansions (business cycle phase classification is taken from NBER). 

Firstly, from the in-sample regressions results, we can see that after the inclusion of dummy variable, YIV and controls lose most of their significance. This is due to the fact that they all possess similar informational content regarding future recessions but especially for the closer time periods, dummy can do so with less error - i.e if the current quarter is a recession, there is a high probability that the next period is also a recession. Nevertheless, as the forecast period increases, the significance and also coefficients decrease, whereas the same figures for YIV increase. Also, as the coefficient for dummy variable is significant throughout the whole forecast horizon, it indicates that structural break in the data exists (implying non-linearities).

Next, we construct out of sample tests. By plotting the root mean squared forecasting errors (RMSFES) in Appendix \@ref(S:rmsfegraph), we find that there indeed exist significant performance asymmetries - during recessionary periods, the model’s accuracy is worse when compared to the expansionary periods. To further illustrate the point, we can analyze predicted vs actual values on Appendix \@ref(S:predictedactuals). The linear model predicts significantly worse around the recessionary periods when compared to expansionary periods. Hence, the results confirm our second hypothesis, i.e. the full-sample is not robust in making predictions during turbulent periods as the accuracy of the model suffers tremendously.

Lastly, we also accept our third hypothesis that the RF model is effective in improving the forecasting performance. In comparison with the linear model, we were able to yield smaller RMSFE’s, most likely due to its ability to take into account non-linearities.  This conclusion can be easily identified by utilizing cumulative sum of squared error differences (Figure: \@ref(fig:CSSFED-lm-rf)) - as the graphs are upward sloping, the interpretation is that on average the RF model has a better forecasting accuracy compared to the linear model. This conclusion can be equated to @Siliverstovs2020 & @Siliverstovs2021, who conclude that the advanced models, in their case DFM, outperform simple linear models. 

Also, it was concluded that the biggest forecasting gains of RF model over the linear model tend to be around market turndowns. On the CSSFED plot, it can be seen that big jumps primarily occur around the recessionary periods. This means that the RF model has superior performance around recessionary periods. To analyze the matter in-depth, the models' predicted values compared to the actual GDP growth can be examined (Appendix  \@ref(S:predictedactuals)). Comparing the two models' predicted and actual values, it can be noticed that RF fails to fully estimate the declines in GDP growth rates during recessions, i.e. it underestimates compared to the linear model. Nevertheless, as the linear model has significant spikes, especially during and after recessions, its overall error is higher. Hence, our results are aligned with the claims of @Chauvet2013, according to whom advanced methods that tackle non-linearities are expected to outperform simple models during turmoils. Also, the fact that RF fails to reach the depths of recessions with its predictions is consistent with @Zhang2012, who states the underestimation during recessionary period is a common problem with RF. As it can be seen from Figure \@ref(fig:pred-vs-actual-rf), RF is not able to reach the depths during recessionary periods when compared to the linear model on Figure \@ref(fig:pred-vs-actual-lm). This stems from the fact that RF cannot extrapolate values outside of the range of values in the training dataset. This, however, isn’t a problem for the linear model. 

## Limitations and further research
The main limitations regarding our work lie in the quality of data - as mentioned in the Data section, the YIV data was behind the paywall, which drastically limited our options with the research (shorter timeframe & only quarterly data). Therefore, as the first step, it would be necessary to obtain the exact data elements required for Black’s formula and then use it to calculate the treasury implied volatility. This would enhance the research in two ways:

1) the data quality is much more reliable, and hence it could improve the outcome of results
2) the scope of the research can be broadened drastically
 
By having the underlying data, the granularity of the work can be improved - for example, one could analyze shorter-term forecasting performance/effects by calculating monthly YIV time series and selecting another proxy for macroeconomic growth that exists on a monthly basis (GDP is available only on a quarterly basis).
 
Secondly, as the data quality is much more robust, an in-depth explanatory analysis could be done. In this research, we rather focus on the "if"-part, but not how - i.e. can YIV predict GDP growth rate taking into account different circumstances. As an extension of the work, one could analyze how exactly YIV affects GDP growth rate in the upcoming periods - since RF itself is very difficult to interpret and is considered to be rather a black-box model, we recommend looking into a method named macroeconomic random forest (MRF) developed by @Coulombe2020^[Author has provided also R package that can be downloaded on request from https://philippegouletcoulombe.com/code]. The main advance in comparison to the RF is that MRF further improves the former by adding a linear component - not only does this help with overfitting of RF, but it also enables the interpretation of the outcome.


