---
title: "borisss"
author: "Karel Räpp, Henry Enno Turu"
date: "14 2 2021"
output: html_document
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(tidyverse)
library(summarytools)
library(kableExtra)
library(dynlm)
library(stats)
library(readr)
library(dplyr)
library(ggplot2)
library(data.table)
library(MacroRF)
require(data.table)
library(zoo)
```

```{r Import Data, include=F}
start <- as.Date("01/03/1990", format="%d/%m/%Y")
end <- as.Date("01/10/2015", format="%d/%m/%Y")

#Import extracted GDP and YIV
dataset <- read_csv("data/gdp_yiv.csv")
dataset$Date <- as.Date(dataset$Date, format="%d.%m.%Y")


#Import extracted GDP and YIV
qoq <- read_csv("data/GDPC1_qoq.csv")
qoq <- qoq %>%
  subset(DATE >= start & DATE <= end) %>%
  rename(quarterly = GDPC1_PCH)

# combine
dataset <- dataset %>%
  mutate(qoq[-1])



#Create rolling averages
dataset <- dataset %>%
  arrange %>%
    mutate(log_gdp=log(1+GDP/100)*100) %>%
    mutate(H4=rollapply(log_gdp, 4, FUN = function(df) mean(df[-5], na.rm = TRUE), fill = NA, align = "left" )) %>%
    mutate(H6=rollapply(log_gdp, 6,FUN = function(df) mean(df[-7], na.rm = TRUE), fill = NA, align = "left" )) %>%
    mutate(H4_2=rollapply(quarterly, 4, FUN = function(df) mean(df[-5], na.rm = TRUE), fill = NA, align = "left" )) %>%
    mutate(H6_2=rollapply(quarterly, 6,FUN = function(df) mean(df[-7], na.rm = TRUE), fill = NA, align = "left" )) 


graph <- ggplot(dataset, aes(x=Date)) + geom_line(aes(y=H4, color="H4")) +geom_line(aes(y=H4_2, color="H4_quarterly")) +geom_line(aes(y=H6,color="H6")) +geom_line(aes(y=H6_2, color="H6_quarterly")) + theme_bw()


```


```{r, include=T}
graph
```




