---
title: "Untitled"
output: 
  bookdown::pdf_document2:
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


The dependent variable CFG-paper is

\begin{align}
\frac{1}{h}\sum_{j=1}^{j=h} \ln (1 + GDP_{t+j})
\end{align}

where $GDP_{t+j}$ is the GDP year-on-year growth rate in quarter $t+j$.

For $h=1$

\begin{align}
\ln (1 + GDP_{t+1}) & = \ln \left(1 + \frac{y_{t+1} - y_{t-3}}{y_{t-3}}\right) = \\
&= \ln \left(1 + \frac{y_{t+1}}{y_{t-3}-1} \right) = \ln \left(\frac{y_{t+1}}{y_{t-3}} \right) = \\
&= \ln y_{t+1} - \ln y_{t-3} = \\
&= \ln y_{t+1} - \ln y_{t} + \ln y_{t} - \ln y_{t-1} + \ln y_{t-1}  - \ln y_{t-2} + \ln y_{t-2} - \ln y_{t-3} = \\
&= (\ln y_{t+1} - \ln y_{t}) + (\ln y_{t} - \ln y_{t-1}) + (\ln y_{t-1}  - \ln y_{t-2}) + (\ln y_{t-2} - \ln y_{t-3}) = \\
&= \Delta \ln y_{t+1} + \Delta \ln y_{t} + \Delta \ln y_{t-1} + \Delta \ln y_{t-2}
\end{align}


For $h=2$

\begin{align}
&\frac{1}{2}( \ln (1 + GDP_{t+2}) + \ln (1 + GDP_{t+1}) ) = \\
&= \frac{1}{2}( \Delta \ln y_{t+2} + \Delta \ln y_{t+1} + \Delta \ln y_{t} + \Delta \ln y_{t-1} +  \Delta \ln y_{t+1} + \Delta \ln y_{t} + \Delta \ln y_{t-1} + \Delta \ln y_{t-2}) =\\
&= \frac{1}{2}( \Delta \ln y_{t+2} + 2\Delta \ln y_{t+1} + 2\Delta \ln y_{t} + 2\Delta \ln y_{t-1} + \Delta \ln y_{t-2}) 
\end{align}


For $h=4$

\begin{align}
&\frac{1}{4}( \ln (1 + GDP_{t+4}) + \ln (1 + GDP_{t+3}) +  \ln (1 + GDP_{t+2}) + \ln (1 + GDP_{t+1})) = \\
&= \frac{1}{4}(
     \Delta \ln y_{t+4} + \Delta \ln y_{t+3} + \Delta \ln y_{t+2} + \Delta \ln y_{t+1} + \\ 
   &+\Delta \ln y_{t+3} + \Delta \ln y_{t+2} + \Delta \ln y_{t+1} + \Delta \ln y_{t} +\\
   &+\Delta \ln y_{t+2} + \Delta \ln y_{t+1} + \Delta \ln y_{t} + \Delta \ln y_{t-1} + \\
   &+\Delta \ln y_{t+1} + \Delta \ln y_{t} + \Delta \ln y_{t-1} + \Delta \ln y_{t-2} + ) =\\
&= \frac{1}{4}( \Delta \ln y_{t+4} +2 \Delta \ln y_{t+3} + 3\Delta \ln y_{t+2} + 4\Delta \ln y_{t+1} + 3\Delta \ln y_{t} + 2\Delta \ln y_{t-1} + \Delta \ln y_{t-2}) 
\end{align}

This formula can be compared with h-step ahead average quarterly growth rate for $h=4$

\begin{align}
&\frac{1}{4}( \ln (1 + GDP_{t+4})) = \\
&= \frac{1}{4}(
     \Delta \ln y_{t+4} + \Delta \ln y_{t+3} + \Delta \ln y_{t+2} + \Delta \ln y_{t+1})
\end{align}

or, h-step ahead quarterly growth rate

\begin{align}
     \Delta \ln y_{t+4} 
\end{align}

Essentially, in CFG the term $4\Delta \ln y_{t+1}$ has the largest weight, whereas the q-on-q growth rate for the most distant quarter $\Delta \ln y_{t+4}$ has the lowest weight. Basically, my idea was that the forecastability at longer horizons in the CFG paper hinges on the fact how well can they can forecast for $h=1$. 