---
title: "Conclusion"
author: "Karel Räpp, Henry Enno Turu"
date: "28 11 2020"
output: 
  bookdown::pdf_document2:
    toc: no
csl: apa.csl
bibliography: library.bib
indent: yes
fontsize: 12pt
geometry: margin = 1in
link-citations: yes
linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \usepackage{microtype}
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage{float}
- \usepackage{amsmath}
- \DeclareMathOperator{\logit}{logit}
---



\linespread{1.6}\selectfont

# Conclusion

The   research sought to discover whether another financial variable, treasury implied volatility (YIV), is able to predict macroeconomic real activity (more specifically the growth rate of GDP). Through replicating the research conducted by @Cremers2021, we validate our first hypothesis that YIV indeed is a significant predictor of macroeconomic real activity as represented by the GDP growth rate throughout the periods from 1 to 12 quarters ahead. Furthermore, we validated that the variable is robust even after controlling for many existing relevant predictors such as term spreads, credit spreads, stock market implied volatility, and number of new residential construction starts.
Next, the aim was to test the robustness of the model and variable with respect to subsample periods (expansionary and recessionary periods) as from recent literature there exists significant evidence that there exist performance asymmetries with respect to subsample periods (e.g. @Siliverstovs2020 research on performance asymmetries). For that, we include a dummy variable to the regression taking a value of 1 during recessions and 0 during expansions (business cycle classification is taken from NBER) and find out that indeed there exist significant performance asymmetries. More specifically, during recessionary periods the model’s accuracy is far worse when compared to the expansionary periods. To further illustrate the point, we plot the values of cumulative sum of squared forecast error differences (CSSFED) for benchmark historic mean model and linear model. As it can be seen from the [?????] there are significant jumps in the graph especially during the 2007-2008 financial crisis – this validates our second hypothesis that the recessionary periods contribute an unproportionally large amount to a model’s accuracy and that there exist substantial performance asymmetries. 
Finally, we proceed to combat the shortcomings of the linear model with the aim to improve the forecast accuracy. For that, we turn our focus on the machine learning (ML) based method, more specifically Random forest (RF) model, which has proven to combat one of the key shortcomings of the linear model – ability to account for non-linearities. Through implementing the random forest model we indeed find confirmation to our third hypothesis that using the model we are able to improve the forecasting accuracy measured through the root mean square forecasting error (RMSFE). Furthermore, when plotting the RF model against the benchmark linear model on the CSSFED graph [????], we see that the graph is upward sloping indicating that the RF model consistently outperforms the linear model.



