---
title: "data_cleaning"
author: "Karel Räpp, Henry Enno Turu"
date: "29 11 2020"
output: 
  bookdown::pdf_document2:
    toc: no
csl: apa.csl
bibliography: library.bib
indent: yes
fontsize: 12pt
geometry: margin = 1in
link-citations: yes
linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \usepackage{microtype}
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage{float}
- \usepackage{amsmath}
- \DeclareMathOperator{\logit}{logit}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(tidyverse)
library(summarytools)
library(kableExtra)
library(dynlm)
library(stats)
library(readr)
library(dplyr)
library(ggplot2)
library(data.table)
library(MacroRF)
require(data.table)
library(zoo)
```

```{r Import Data, include=F}
start <- as.Date("01/03/1990", format="%d/%m/%Y")
end <- as.Date("01/10/2015", format="%d/%m/%Y")

#Import extracted GDP and YIV
dataset <- read_csv("data/gdp_yiv.csv")
dataset$Date <- as.Date(dataset$Date, format="%d.%m.%Y")


#Import Housing data and convert to quarterly
housng <- read_csv("data/HOUSNG.csv")
housng$DATE <- as.Date(housng$DATE, format="%d.%m.%Y")

housng_qrt <- housng %>%
  group_by(quarter=paste(quarters(DATE), lubridate::year(DATE))) %>%
  summarise(housng = sum(HOUSNG))

housng_qrt$DATE <- as.Date(as.yearqtr(housng_qrt$quarter, format = "Q%q %Y"))
housng_qrt <- housng_qrt %>%
  select(-quarter) %>%
  subset(DATE >= start & DATE <= end)


# Import VIX anx convert to quarterly
vixcurrent <- read_csv("data/vixcurrent.csv") #Current VIX methodology
vixarchive <- read_csv("data/vixarchive.csv") #Current applied retrospectively

vixcurrent$Date <- as.Date(vixcurrent$Date, format="%m/%d/%Y")
vixarchive$Date <- as.Date(vixarchive$Date, format="%d.%m.%Y")

vix <-rbind(vixarchive, vixcurrent)
vix <- vix %>%
  select(VIX='VIX Close', 'Date') %>%
  mutate(month=month(Date)) %>%
  mutate(year=year(Date))
  
vix_monthly <- aggregate(VIX ~ month + year, vix, mean)

vix_qrt<- vix_monthly  %>%
  mutate(DATE=as.Date(paste(year,month,"01", sep="/"))) %>%
  select(-month, -year)  %>%
  group_by(quarter = paste(quarters(DATE), lubridate::year(DATE))) %>%
  summarise(VIX = mean(VIX)) 


vix_qrt$DATE <- as.Date(as.yearqtr(vix_qrt$quarter, format = "Q%q %Y"))
vix_qrt <- vix_qrt %>%
  select(-quarter) %>%
  subset(DATE >= start & DATE <= end)

# Import credit rates, add frac=1 for month end. Data ends in 2010??
moodys.raw <- read_csv("Data/moodys.csv")
creditspreads<- subset(moodys.raw, DATE >= start & DATE <= end)
creditspreads$AAA <- as.numeric(creditspreads$AAA)
creditspreads$DBAA <- as.numeric(creditspreads$DBAA)
creditspreads <- creditspreads %>%
  mutate(baa_aaa=DBAA-AAA)


GZ.raw <- read_csv("Data/GZ_quarterly.csv")
GZ.raw$Date <- as.Date(as.yearqtr(GZ.raw$date, format = "%YQ%q"))
GZ <- subset(GZ.raw, Date >= start & Date <=end)
GZ <- GZ %>%
  select(Date, gz_spr)

# Import term rates
DGS.raw <- read_csv("Data/feds/DGS_combined.csv")
DGS.clean<- subset(DGS.raw, DATE >= start & DATE <= end)

DGS.clean$DGS3MO <- as.numeric(DGS.clean$DGS3MO)
DGS.clean$DGS6MO <- as.numeric(DGS.clean$DGS6MO)

DGS.clean <- DGS.clean %>%
  mutate(TRM0503 = DGS5-DGS3MO) %>%
  mutate(TRM0506 = DGS5-DGS6MO) %>%
  mutate(TRM1003 = DGS10-DGS3MO) %>%
  mutate(TRM1006 = DGS10-DGS6MO) %>%
  mutate(TRM1012 = DGS10-DGS1) %>%
  mutate(SRT03M = DGS3MO-lag(DGS3MO))

#SPY
spy <- read_csv("data/SPY.csv")
spy <- spy %>%
  select(Date, Close) %>%
  group_by(quarter=paste(quarters(Date), lubridate::year(Date))) %>%
  summarise_at(c("Close"), sum)
spy$Date <- as.Date(as.yearqtr(spy$quarter, format = "Q%q %Y"))
spy <- spy%>%
  select(-quarter) %>%
  subset(Date >= start & Date <= end) %>%
  rename(spy=Close)

#Dependent variables
dependent_monthly<- read_csv("data/dependent.csv")
dependent_monthly$DATE <- as.Date(dependent_monthly$DATE, origin = "1899-12-30")

dependent_qrt <- dependent_monthly %>%
  group_by(quarter=paste(quarters(DATE), lubridate::year(DATE))) %>%
  summarise_at(c("CON","EMP","IND"), sum)


dependent_qrt$DATE <- as.Date(as.yearqtr(dependent_qrt$quarter, format = "Q%q %Y"))
dependent_qrt <- dependent_qrt %>%
  select(-quarter) %>%
  subset(DATE >= start & DATE <= end)

#Import NBER recessions and create subsets
dummy <- read.csv("data/Dummy.csv")

# combine
dataset <- dataset %>%
  mutate(DGS.clean[-1]) %>% 
  mutate(creditspreads[-1]) %>%
  mutate(dum=dummy$Reccession) %>%
  mutate(dependent_qrt[-4]) %>%
  mutate(vix_qrt[-2]) %>%
  mutate(housng_qrt[-2]) %>%
  mutate(log_gdp=log(1+GDP/100)*100) %>%
  left_join(GZ) %>% 
  left_join(spy) %>%
  relocate(Date, YIV, GDP, CON, EMP, IND)

#Create rolling averages
dataset <- dataset %>%
  arrange %>%
    mutate(H4=rollapply(log_gdp,5,FUN = function(df) mean(df[-5], na.rm = TRUE), fill = NA, align = "left" )) %>%
    mutate(H6=rollapply(log_gdp, 7,FUN = function(df) mean(df[-7], na.rm = TRUE), fill = NA, align = "left" )) %>%
    mutate(H8=rollapply(log_gdp, 9,FUN = function(df) mean(df[-9], na.rm = TRUE), fill = NA, align = "left" )) %>%
    mutate(H10=rollapply(log_gdp, 11,FUN = function(df) mean(df[-11], na.rm = TRUE), fill = NA, align = "left" )) %>%
    mutate(H12=rollapply(log_gdp, 13,FUN = function(df) mean(df[-13], na.rm = TRUE), fill = NA, align = "left" )) %>%
    mutate(F1=lead(log_gdp, n = 1L)) %>%
    mutate(F2=lead(log_gdp, n = 2L)) %>%
    mutate(F3=lead(log_gdp, n = 3L)) %>%
    mutate(F4=lead(log_gdp, n = 4L)) %>%
    mutate(F5=lead(log_gdp, n = 5L)) %>%
    mutate(F6=lead(log_gdp, n = 6L)) %>%
    mutate(F7=lead(log_gdp, n = 7L)) %>%
    mutate(F8=lead(log_gdp, n = 8L)) %>%
    mutate(F9=lead(log_gdp, n = 9L)) %>%
    mutate(F10=lead(log_gdp, n = 10L)) %>%
    mutate(F11=lead(log_gdp, n = 11L)) %>%
    mutate(F12=lead(log_gdp, n = 12L))


#Name differences with appendices
df <- dataset 
df.expansionary <- subset(dataset, dum== 0)
df.recessionary <- subset(dataset, dum== 1)

#drop unnecessary shit for work proccesses
rm(list=setdiff(ls(), c("df")))

df <- df %>%
  mutate(lag1=lag(log_gdp, n = 1L)) %>%
  mutate(lag2=lag(log_gdp, n = 2L)) %>%
  mutate(lag3=lag(log_gdp, n = 3L)) %>%
  mutate(lag4=lag(log_gdp, n = 4L))


df_summary <- df %>%
  select("YIV", "GDP", "CON", "EMP", "IND", "spy", "VIX","DBAA","AAA","baa_aaa","gz_spr", "housng" , "SRT03M", "TRM1003", "TRM1006", "TRM1012", "TRM0503", "TRM0506")

df <- df %>%
  mutate_if(is.numeric, scale)


```




