---
title: "Discussion"
author: "Karel Räpp, Henry Enno Turu"
date: "28 11 2020"
output: 
  bookdown::pdf_document2:
    toc: no
csl: apa.csl
bibliography: library.bib
indent: yes
fontsize: 12pt
geometry: margin = 1in
link-citations: yes
linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \usepackage{microtype}
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage{float}
- \usepackage{amsmath}
- \DeclareMathOperator{\logit}{logit}
---



\linespread{1.6}\selectfont

# Discussion
 
In the following section, we offer context from the literature review to our findings. The goal is to analyze how our findings fit in with the existing research by other academia. Secondly, we give an overview of the limitations of our research and additionally, suggest opportunities for further research of this topic.

## Discussion of results

On the basis of the results stated previously, we can accept the stated hypothesis 1 that treasury implied volatility is indeed a significant predictor of throughout the periods from 1 to 8 quarters ahead. This outcome is robust even after including various control variables that have been historically important predictors of real output such as term spreads, credit spreads, stock market implied volatility, and number of new residential construction starts. The latter indicates that although accounting for many of the most significant variables, the YIV’s predictive ability still persists meaning that YIV can be considered as a solid indicator of GDP growth.
Our results are consistent with the paper by Cremers et al. (2017) while the only difference arises is from std. error. Thus, this verifies the validity of our methodology and that the extracted data can be used to proceed with the research process.

Next, the aim was to test the robustness of the model and variable with respect to subsample periods (expansionary and recessionary periods) as from recent literature there exists significant evidence that there exist performance asymmetries with respect to subsample periods (@Chauvet2013, who conclude that GDP growth is significantly differ to forecast during recessions.). For that, we include a dummy variable to the regression taking a value of 1 during recessions and 0 during expansions (business cycle classification is taken from NBER) and find out that indeed there exist significant performance asymmetries. More specifically, during recessionary periods the model’s accuracy is far worse when compared to the expansionary periods. To further illustrate the point, we plot the root mean squared forecasting errors (RMSFEs) in figure \@ref(fig:oosgraph)). As it can be seen from the graph the linear model predicts significantly worse during the recessionary time periods when compared to expansionary and full sample periods. Hence, the results confirm our second hypothesis i.e. the full-sample is not robust in making predictions during turbulent time periods as the accuracy of the model suffers tremendously.

Lastly, we also accept our last hypothesis that machine learning models which in Random Forest can improve the forecast performance. In comparison with OLS model, we were able to yield smaller RMSFE’s, most likely to its ability to take into account non-linearities.  This conclusion can be easily identified by utilizing cumulative sum of squared error differences (Figure: \@ref(fig:CSSFED-lm-rf)) - as the graphs are upward sloping, the interpretation is that on average for each observation the random forest model has a better forecast accuracy compared to the linear model. This conclusion can be equated to @Siliverstovs2020 & @Siliverstovs2021 who conclude that the advanced models advanced models, specifically DFM in their case outperform simple linear models. 

However, it was also cocnluded that the biggest forecasting gains of advanced models tend to be around market turndowns. This . On the CSSFED plot, it can be seen that during recessionary periods, there exist multiple drops, which means that that during each of the observations random forest has had relatively worse performance. To analyze the matter in depth, one can analyze the models predicted values compared to the actual GDP growth(Figure: \@ref(fig:pred-vs-actual-rf)). Compared to linear models actual vs predicted values (Figure :\@ref(fig:pred-vs-actual-lm)) it can be noticed that random forest fails to estimate the declines in GDP during recessions - i.e. it underestimates compared to linear model. Hence, our results regarding this part do not match.
Even so, there exist contradicting views from the academia, from one side @Siliverstovs2020 & @Siliverstovs2021 and @Chauvet2013 according to whom advanced methods that tackle non-linearities are expected to outperform simple models during turmoils and opposedly @Zhang2012 who states the underestimation is a common problem with random forest. To elaborate, this happens due to its algorithms as it uses averaging when making predictions - thus, the extreme values tend to be underestimated and smaller values overestimated which is consistent with our results. 

## Limitations & further research
The main limitations regarding our work lie in the data quality - as mentioned in the Data section the data was behind the paywall, which drastically limited our options with the research (shorter timeframe & only quarterly data). Therefore, as the first step it would be necessary to obtain the exact data elements required for Black’s formula, and then use it to calculate the treasury implied volatility. This would enhance the research in two ways - 
1) the data quality is much more reliable and hence it could improve the outcome of results
2) the scope of the research can be broadened drastically
 
By having the underlying data, the granularity of the work can be improved - for example, one could analyze shorter-term forecasting performance/effects by calculating monthly YIV timeseries and selecting another proxy for macroeconomic growth that exists on a monthly basis (GDP available only quarterly).
 
Secondly, as the data quality is much more robust, in-depth explanatory analysis could be done. In this research, we rather focus on the "if"-part, but not how - i.e. can YIV predict GDP taking into account different circumstances. As an extension of the work, one could analyze how exactly YIV affects GDP in the upcoming periods - since random forest itself is very difficult to interpret and is considered to be rather a black-box model, we recommend to look into a method named macroeconomic random forest (MRF) developed by @Coulombe2020^[Author has provided also R package that can be downloaded on request from https://philippegouletcoulombe.com/code]. The main advances in comparison to random forest is that MRF further improves the former by adding a linear component - not only does this help with overfitting of RF but it also enables the interpretation of the outcome.


