---
title: "Appendices"
date: "12.11-2020"
output: 
  bookdown::pdf_document2:
    toc: no
csl: apa.csl
bibliography: library.bib
indent: yes
fontsize: 12pt
geometry: margin = 1in
link-citations: yes
linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \usepackage{microtype}
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage{float}
- \usepackage{amsmath}
- \DeclareMathOperator{\logit}{logit}
---

# Appendices
```{r run libraries, include=F}
library(stringr)
library(tidyverse)
library(summarytools)
library(kableExtra)
library(dynlm)
library(stats)
library(readr)
library(dplyr)
library(ggplot2)
library(data.table)
library(MacroRF)
require(data.table)
library(zoo)
library(sandwich)
```

```{r child = 'Dataclean.rmd'}
```


```{r create_log, include=F}
df <- df %>%
  mutate(log_gdp=log(1+GDP/100)*100)

df <- df %>%
  arrange %>%
    mutate(H12=rollapply(log_gdp,5,FUN = function(df) mean(df[-5], na.rm = TRUE), fill = NA, align = "left" )) %>%
    mutate(H18=rollapply(log_gdp, 7,FUN = function(df) mean(df[-7], na.rm = TRUE), fill = NA, align = "left" )) %>%
    mutate(H24=rollapply(log_gdp, 9,FUN = function(df) mean(df[-9], na.rm = TRUE), fill = NA, align = "left" )) %>%
    mutate(H30=rollapply(log_gdp, 11,FUN = function(df) mean(df[-11], na.rm = TRUE), fill = NA, align = "left" )) %>%
    mutate(H36=rollapply(log_gdp, 13,FUN = function(df) mean(df[-13], na.rm = TRUE), fill = NA, align = "left" ))

dummy <- read.csv("Dummy.csv")

df <- df %>%
  mutate(dum = dummy$Reccession)

df.expansionary <- subset(df, dum== 0)
df.recessionary <- subset(df, dum== 1)

```




```{r reg_output, include=F}
# Out-of-sample regression
do_regression <- function(var)
{ # var - the name of the variable to be regressed
  res <- dynlm(as.formula(paste0(var, "~ YIV")), df[1:50,]) # run linear regression
  predicted <- predict(res, df[51:99,], type = "response")
  actual <- df[51:99, var]
  results <- sqrt((predicted-actual)^2)
  RMSFE <- sapply(results, mean, na.rm = TRUE)
return(RMSFE)
}

# In-sample regression
do_regression2 <- function(var2)
{ 
  res2 <- dynlm(as.formula(paste0(var2, "~ YIV")), df[1:99,]) # run linear regression
  predicted2 <- predict(res2, df[51:99,], type = "response")
  actual2 <- df[51:99, var2]
  results2 <- sqrt((predicted2-actual2)^2)
  RMSFE2 <- sapply(results2, mean, na.rm = TRUE)
return(RMSFE2)
}

# Out-of-sample expansionary regression
do_regression3 <- function(var3)
{ 
  res3 <- dynlm(as.formula(paste0(var3, "~ YIV")), df.expansionary[1:50,]) # run linear regression
  predicted3 <- predict(res3, df.expansionary[51:91,], type = "response")
  actual3 <- df.expansionary[51:91, var3]
  results3 <- sqrt((predicted3-actual3)^2)
  RMSFE3 <- sapply(results3, mean, na.rm = TRUE)
return(RMSFE3)
}

# Out-of-sample recessionary regression
do_regression4 <- function(var4)
{ 
  res4 <- dynlm(as.formula(paste0(var4, "~ YIV")), df.recessionary[1:6,]) # run linear regression
  predicted4 <- predict(res4, df.expansionary[6:12,], type = "response")
  actual4 <- df.expansionary[6:12, var4]
  results4 <- sqrt((predicted4-actual4)^2)
  RMSFE4 <- sapply(results4, mean, na.rm = TRUE)
return(RMSFE4)
}

# In-sample expansionary regression
do_regression5 <- function(var5)
{ 
  res5 <- dynlm(as.formula(paste0(var5, "~ YIV")), df.expansionary[1:91,]) # run linear regression
  predicted5 <- predict(res5, df.expansionary[51:91,], type = "response")
  actual5 <- df.expansionary[51:91, var5]
  results5 <- sqrt((predicted5-actual5)^2)
  RMSFE5 <- sapply(results5, mean, na.rm = TRUE)
return(RMSFE5)
}

# In-sample recessionary regression
do_regression6 <- function(var6)
{ 
  res6 <- dynlm(as.formula(paste0(var6, "~ YIV")), df.recessionary[1:91,]) # run linear regression
  predicted6 <- predict(res6, df.expansionary[51:91,], type = "response")
  actual6 <- df.expansionary[51:91, var6]
  results6 <- sqrt((predicted6-actual6)^2)
  RMSFE6 <- sapply(results6, mean, na.rm = TRUE)
return(RMSFE6)
}


df_results1 <- as.data.frame(t(sapply(colnames(df)[5:9], do_regression)))
df_results2 <- as.data.frame(t(sapply(colnames(df)[5:9], do_regression2)))
df_results3 <- as.data.frame(t(sapply(colnames(df)[5:9], do_regression3)))
df_results4 <- as.data.frame(t(sapply(colnames(df)[5:9], do_regression4)))
df_results5 <- as.data.frame(t(sapply(colnames(df)[5:9], do_regression5)))
df_results6 <- as.data.frame(t(sapply(colnames(df)[5:9], do_regression6)))

df_results <- rbind(df_results1, df_results2, df_results3, df_results4, df_results5, df_results6)

df_results <- df_results %>%
  round(2)

colnames(df_results, do.NULL = FALSE)
colnames(df_results) <- c("H12","H18","H24","H30","H36")
rownames(df_results) <- c("Out-of-sample RMSFE", "In-sample RMSFE", "Out-of-sample expansionary RMSFE", "Out-of-sample recessionary RMSFE", "In-sample expansionary RMSFE", "In-sample recessionary RMSFE")

```


## Out-of-sample test. 

```{r tableOLS, message = F, warnings = F,echo = F}
df_results %>%
  kbl() %>%
  kable_styling()
```




