---
title: "Appendices"
date: "12.11-2020"
output: 
  bookdown::pdf_document2:
    toc: no
csl: apa.csl
bibliography: library.bib
indent: yes
fontsize: 12pt
geometry: margin = 1in
link-citations: yes
linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \usepackage{microtype}
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage{float}
- \usepackage{amsmath}
- \DeclareMathOperator{\logit}{logit}
---

# Appendices
```{r run libraries, include=F}
library(stringr)
library(tidyverse)
library(summarytools)
library(kableExtra)
library(dynlm)
library(stats)
library(readr)
library(dplyr)
library(ggplot2)
library(data.table)
library(MacroRF)
require(data.table)
library(zoo)
library(rollRegres)
library(sandwich)
library(modelr)
library(Metrics)
library(mltools)
library(tibble)
library(data.table)
library(reshape2)
```

```{r child = 'Dataclean.rmd'}
```


```{r create_log, include=F}
df <- df %>%
  mutate(log_gdp=log(1+GDP/100)*100)


df <- df %>%
   arrange %>%
     mutate(H3=lead(log_gdp, n = 1L)) %>%
     mutate(H6=lead(log_gdp, n = 2L)) %>%
     mutate(H9=lead(log_gdp, n = 3L)) %>%
     mutate(H12=lead(log_gdp, n = 4L)) %>%
     mutate(H15=lead(log_gdp, n = 5L)) %>%
     mutate(H18=lead(log_gdp, n = 6L)) %>%
     mutate(H21=lead(log_gdp, n = 7L)) %>%
     mutate(H24=lead(log_gdp, n = 8L)) %>%
     mutate(H27=lead(log_gdp, n = 9L)) %>%
     mutate(H30=lead(log_gdp, n = 10L)) %>%
     mutate(H33=lead(log_gdp, n = 11L)) %>%
     mutate(H36=lead(log_gdp, n = 12L))


dummy <- read.csv("Dummy.csv")
df <- df %>%
  mutate(dum = dummy$Reccession)

start <- as.Date("01/03/1990", format="%d/%m/%Y")
end <- as.Date("01/10/2015", format="%d/%m/%Y")

DGS.raw <- read_csv("data/feds/DGS_combined.csv")
DGS.clean<- subset(DGS.raw, DATE >= start)
DGS.clean <- subset(DGS.clean, DATE <= end)


DGS.clean$DGS3MO <- as.numeric(DGS.clean$DGS3MO)
DGS.clean$DGS6MO <- as.numeric(DGS.clean$DGS6MO)

DGS.clean <- DGS.clean %>%
  mutate(TRM0503 = DGS5-DGS3MO) %>%
  mutate(TRM0506 = DGS5-DGS6MO) %>%
  mutate(TRM1003 = DGS10-DGS3MO) %>%
  mutate(TRM1006 = DGS10-DGS6MO) %>%
  mutate(TRM1012 = DGS10-DGS1) %>%
  mutate(SRT03M = DGS3MO-lag(DGS3MO))
  

# Import credit rates, add frac=1 for month end. Data ends in 2010??
moodys.raw <- read_csv("Data/moodys.csv")
creditspreads<- subset(moodys.raw, DATE >= start & DATE <= end)
creditspreads$AAA <- as.numeric(creditspreads$AAA)
creditspreads$DBAA <- as.numeric(creditspreads$DBAA)

df.expansionary <- subset(df, dum== 0)
df.recessionary <- subset(df, dum== 1)

df <- df %>%
  mutate(creditspreads[-1]) %>%
  mutate(DGS.clean[-1:-6])




colnames(df)
col_order <- c("Date", "GDP", "YIV", "dum", "log_gdp", "H3", "H6", "H9", "H12", "H15", "H18", "H21", "H24", "H27", "H30", "H33", "H36", "AAA", "DBAA", "TRM0503", "TRM0506", "TRM1003", "TRM1006","TRM1012", "SRT03M")
df <- df[, col_order]

```




```{r reg_output, include=F}

# Out-of-sample regression
do_regression <- function(var)
{ # var - the name of the variable to be regressed
  res <-roll_regres(as.formula(paste0(var, "~ YIV")), df[1:91,], width=20L, do_compute = c("sigmas", "r.squareds", "1_step_forecasts"))
  predicted <- unlist(res[4])
  predicted <- predicted[21:91]
  actual <- df[[var]][21:91]
  RMSFE <- rmse(preds = predicted, actuals = actual)
return(RMSFE)
}


# Out-of-sample regression
do_regression2 <- function(var)
{ # var - the name of the variable to be regressed
  res <-roll_regres(as.formula(paste0(var, "~ YIV")), df[1:91,], width=20L, do_compute = c("sigmas", "r.squareds", "1_step_forecasts"))
  predicted <- unlist(res[4])
  predicted <- predicted[21:91]
  actual <- df[[var]][21:91]
  SE <- (predicted-actual)^2
  SE <- SE[c(25,26,27,52,53,54,55,56,57)]
  RMSFE <- sqrt(mean(SE))
return(RMSFE)
}


# Out-of-sample regression
do_regression3 <- function(var)
{ # var - the name of the variable to be regressed
  res <-roll_regres(as.formula(paste0(var, "~ YIV")), df[1:91,], width=20L, do_compute = c("sigmas", "r.squareds", "1_step_forecasts"))
  predicted <- unlist(res[4])
  predicted <- predicted[21:91]
  actual <- df[[var]][21:91]
  SE <- (predicted-actual)^2
  SE <- SE[-c(25,26,27,52,53,54,55,56,57)]
  RMSFE <- sqrt(mean(SE))
return(RMSFE)
}


# Out-of-sample regression
do_regression4 <- function(var)
{ # var - the name of the variable to be regressed
  res <-roll_regres(as.formula(paste0(var, "~ log_gdp")), df[1:91,], width=20L, do_compute = c("sigmas", "r.squareds", "1_step_forecasts"))
  predicted <- unlist(res[4])
  predicted <- predicted[21:91]
  actual <- df[[var]][21:91]
  RMSFE <- rmse(preds = predicted, actuals = actual)
return(RMSFE)
}

# TRM1006 doesn't work in the regression for some reason
do_regression5 <- function(var)
{ # var - the name of the variable to be regressed
  res <-roll_regres(as.formula(paste0(var, "~ TRM0503 + TRM0506 + TRM1003 + TRM1012")), df[1:91,], width=20L, do_compute = c("sigmas", "r.squareds", "1_step_forecasts"))
  predicted <- unlist(res[4])
  predicted <- predicted[21:91]
  actual <- df[[var]][21:91]
  RMSFE <- rmse(preds = predicted, actuals = actual)
return(RMSFE)
}

# do_regression6 <- function(var)
# { # var - the name of the variable to be regressed
#   res <-roll_regres(as.formula(paste0(var, "~ SRT03M")), df[1:91,], width=20L, do_compute = c("sigmas", "r.squareds", "1_step_forecasts"))
#   predicted <- unlist(res[4])
#   predicted <- predicted[21:91]
#   actual <- df[[var]][21:91]
#   RMSFE <- rmse(preds = predicted, actuals = actual)
# return(RMSFE)
# }


do_regression7 <- function(var)
{ # var - the name of the variable to be regressed
  res <-roll_regres(as.formula(paste0(var, "~ AAA + DBAA")), df[1:91,], width=20L, do_compute = c("sigmas", "r.squareds", "1_step_forecasts"))
  predicted <- unlist(res[4])
  predicted <- predicted[21:91]
  actual <- df[[var]][21:91]
  RMSFE <- rmse(preds = predicted, actuals = actual)
return(RMSFE)
}

df_results1 <- as.data.frame(t(sapply(colnames(df)[6:17], do_regression)))
df_results2 <- as.data.frame(t(sapply(colnames(df)[6:17], do_regression2)))
df_results3 <- as.data.frame(t(sapply(colnames(df)[6:17], do_regression3)))
df_results4 <- as.data.frame(t(sapply(colnames(df)[6:17], do_regression4)))
df_results5 <- as.data.frame(t(sapply(colnames(df)[6:17], do_regression5)))
#df_results6 <- as.data.frame(t(sapply(colnames(df)[6:17], do_regression6)))
df_results7 <- as.data.frame(t(sapply(colnames(df)[6:17], do_regression7)))



df_resultss <- rbind(df_results1, df_results2, df_results3, df_results4, df_results5, df_results7)

df_resultss <- df_resultss %>%
  round(2)

colnames(df_resultss, do.NULL = FALSE)
colnames(df_resultss) <- c("H3","H6","H9","H12","H15","H18","H21","H24","H27","H30","H33","H36")
rownames(df_resultss) <- c("Out-of-sample RMSFE", "Recessionary", "Expansionary" ,"Naive", "TRM", "CRS")

```


## Out-of-sample test. 

```{r tableOLS, message = F, warnings = F,echo = F}
df_resultss %>%
  kbl() %>%
  kable_styling()

df_results <- transpose(df_resultss)

df_resultss2 <- melt(df_resultss)
df_resultss2$rowid <- c("Out-of-sample RMSFE", "Recessionary", "Expansionary" ,"Naive", "TRM", "CRS")

ggplot(df_resultss2, aes(variable, value, group=factor(rowid))) + geom_line(aes(color=factor(rowid)))

```





