---
title: "TIV"
output: 
  bookdown::pdf_document2:
    toc: no
indent: yes
fontsize: 12pt
geometry: margin = 1in
link-citations: yes
linkcolor: blue
urlcolor: blue
header-includes:
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \usepackage{microtype}
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage{float}
- \usepackage{amsmath}
- \DeclareMathOperator{\logit}{logit}
---

# Appendices
```{r run libraries, include=F}
library(stringr)
library(tidyverse)
library(summarytools)
library(kableExtra)
library(dynlm)
library(stats)
library(readr)
library(dplyr)
library(ggplot2)
library(data.table)
library(MacroRF)
require(data.table)
library(zoo)
```


```{r create_log, include=F}

df2 <- read.csv("TIV_GDP.csv")
df2$Date <- as.Date(df2$Date, origin = "1899-12-30")


df2 <- df2 %>%
  arrange %>%
    mutate(H12=lead(rollapply(GDP, 13, FUN = function(df2) mean(df2[-13], na.rm = TRUE), fill = NA, align = "left" ))) %>%
      mutate(H18=lead(rollapply(GDP, 19,FUN = function(df2) mean(df2[-19], na.rm = TRUE), fill = NA, align = "left" ))) %>%
        mutate(H24=lead(rollapply(GDP, 25,FUN = function(df2) mean(df2[-25], na.rm = TRUE), fill = NA, align = "left" ))) %>%
          mutate(H30=lead(rollapply(GDP, 31,FUN = function(df2) mean(df2[-31], na.rm = TRUE), fill = NA, align = "left" )))
```

```{r}
#create lags
df2 <- df2 %>%
  mutate(TIV_lag1=lag(TIV,1)) %>%
  mutate(TIV_lag2=lag(TIV,2)) %>%
  mutate(TIV_lag3=lag(TIV,3)) %>%
  mutate(TIV_lag4=lag(TIV,4)) %>%
  mutate(TIV_lag5=lag(TIV,5)) %>%
  mutate(TIV_lag6=lag(TIV,6)) %>%
  mutate(TIV_lag7=lag(TIV,7)) %>%
  mutate(TIV_lag8=lag(TIV,8)) %>%
  mutate(TIV_lag9=lag(TIV,9)) %>%
  mutate(TIV_lag10=lag(TIV,10))

TIV_graph <- ggplot(df2,aes(x=Date, y=TIV)) + geom_path()
print(TIV_graph)
```



```{r lagsregression}
summary(df2)

do_regression <- function(var)
  { # var - the name of the variable to be regressed
    res <- dynlm(as.formula(paste0("H12 ~", var)), df2) # run linear regression
    coefs <- c("R-Squared"= summary(res)$r.squared*100,"Beta" = summary(res)$coefficients[2], "P-value"= summary(res)$coefficients[,3])
  return(coefs)
  }

output_lagsregression2 <- as.data.frame(t(sapply(colnames(df2)[9:17], do_regression)))


barplot(output_lagsregression2$'R-Squared')
```

```{r reg_output, include=F}
# define a function to get coefficients from linear regression
  
do_regression <- function(var)
  { # var - the name of the variable to be regressed
    res <- dynlm(as.formula(paste0(var, "~ TIV")), df2) # run linear regression
    coefs <- c("R-Squared"= summary(res)$r.squared, "Intercept" = summary(res)$coefficients[1], "Beta" = summary(res)$coefficients[2], "t-statistic" = summary(res)$coefficients[,3]) 
  return(coefs)
  }

df_results <- as.data.frame(t(sapply(colnames(df2)[4:7], do_regression)))
#sapply : applies on "var3"(first YIV) ..."var23"(last)  the function do_lm
#t() transposes

df_results <- df_results %>%
  round(2)
```




## Appendix B. 

```{r tableOLS, message = F, warnings = F,echo = F}
kbl(cbind(t(df_results)), booktabs = T, longtable=T, align="c", digits=2, caption="Regression output") %>%
   kable_styling(latex_options = c("striped"), full_width = TRUE) %>%
     pack_rows("Panel A: TIV",1,3, latex_align="c") %>%
       footnote(general = "Preliminary regression output. Initial data needs to be re-checked.")

```
